global:
  scrape_interval: 30s


scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://app:8001/health
        - http://google.com
        - http://no-way-not-exists123123123.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: node
    static_configs:
    - targets: ['node_exporter:9100']


